ALTER TABLE users 
ADD COLUMN IF NOT EXISTS is_transactions_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_reporting_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_notification_enabled BOOLEAN DEFAULT FALSE;
